package com.citi.shanghai.training.dataAnalyst.dao;

import com.citi.shanghai.training.dataAnalyst.model.AggsByDay;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AggsByDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    int insert(AggsByDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    int insertSelective(AggsByDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    AggsByDay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AggsByDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggsByDay
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AggsByDay record);

    List<AggsByDay> getAllPriceByDay(@Param("startDay") int fromDate, @Param("endDay") int toDate, @Param("symbols") List<String> symbols);
}