package com.citi.shanghai.training.dataAnalyst.dao;

import com.citi.shanghai.training.dataAnalyst.model.CalendarDate;

public interface CalendarDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String calendardate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int insert(CalendarDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int insertSelective(CalendarDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    CalendarDate selectByPrimaryKey(String calendardate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CalendarDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calendar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CalendarDate record);
}