package com.citi.shanghai.training.dataAnalyst.dao;

import com.citi.shanghai.training.dataAnalyst.model.PortfolioSymbols;

import java.util.List;

public interface PortfolioSymbolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer portfolioid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    int insert(PortfolioSymbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    int insertSelective(PortfolioSymbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    PortfolioSymbols selectByPrimaryKey(Integer portfolioid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PortfolioSymbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolioWithSymbols
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PortfolioSymbols record);

    List<PortfolioSymbols> getSymbolsByPortfolioId(Integer portfolioId);
}