package com.citi.shanghai.training.dataAnalyst.dao;

import java.util.List;

public interface PortfolioMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer portfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    int insert(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    int insertSelective(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    Portfolio selectByPrimaryKey(Integer portfolioId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Portfolio record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portfolios
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Portfolio record);

    List<Portfolio> selectPortfolioByUserId(Integer userId);

}