package com.citi.shanghai.training.dataAnalyst.dao;

import com.citi.shanghai.training.dataAnalyst.model.Recoards;

import java.util.List;

public interface RecoardsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int insert(Recoards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int insertSelective(Recoards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    Recoards selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recoards record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recoards record);
}