package com.citi.shanghai.training.dataAnalyst.dao;

import com.citi.shanghai.training.dataAnalyst.model.Symbols;

import java.util.List;

public interface SymbolsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Object symbolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    int insert(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    int insertSelective(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    Symbols selectByPrimaryKey(Object symbolId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Symbols record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table symbols
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Symbols record);

    List<Symbols> getAllSymbols();
}