package com.citi.shanghai.training.dataAnalyst.model;

import java.math.BigDecimal;

public class AggsByHour {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.symbolID
     *
     * @mbggenerated
     */
    private Integer symbolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Date
     *
     * @mbggenerated
     */
    private Integer date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Time
     *
     * @mbggenerated
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.High
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.SplitFactor
     *
     * @mbggenerated
     */
    private Double splitfactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Earnings
     *
     * @mbggenerated
     */
    private Integer earnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByHour.Dividends
     *
     * @mbggenerated
     */
    private Double dividends;

    private Double increasePercentage;

    public Double getIncreasePercentage() {
        return increasePercentage;
    }

    public void setIncreasePercentage(Double increasePercentage) {
        this.increasePercentage = increasePercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.ID
     *
     * @return the value of aggsByHour.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.ID
     *
     * @param id the value for aggsByHour.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.symbolID
     *
     * @return the value of aggsByHour.symbolID
     *
     * @mbggenerated
     */
    public Integer getSymbolid() {
        return symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.symbolID
     *
     * @param symbolid the value for aggsByHour.symbolID
     *
     * @mbggenerated
     */
    public void setSymbolid(Integer symbolid) {
        this.symbolid = symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Date
     *
     * @return the value of aggsByHour.Date
     *
     * @mbggenerated
     */
    public Integer getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Date
     *
     * @param date the value for aggsByHour.Date
     *
     * @mbggenerated
     */
    public void setDate(Integer date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Time
     *
     * @return the value of aggsByHour.Time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Time
     *
     * @param time the value for aggsByHour.Time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Open
     *
     * @return the value of aggsByHour.Open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Open
     *
     * @param open the value for aggsByHour.Open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.High
     *
     * @return the value of aggsByHour.High
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.High
     *
     * @param high the value for aggsByHour.High
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Low
     *
     * @return the value of aggsByHour.Low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Low
     *
     * @param low the value for aggsByHour.Low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Close
     *
     * @return the value of aggsByHour.Close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Close
     *
     * @param close the value for aggsByHour.Close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Volume
     *
     * @return the value of aggsByHour.Volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Volume
     *
     * @param volume the value for aggsByHour.Volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.SplitFactor
     *
     * @return the value of aggsByHour.SplitFactor
     *
     * @mbggenerated
     */
    public Double getSplitfactor() {
        return splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.SplitFactor
     *
     * @param splitfactor the value for aggsByHour.SplitFactor
     *
     * @mbggenerated
     */
    public void setSplitfactor(Double splitfactor) {
        this.splitfactor = splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Earnings
     *
     * @return the value of aggsByHour.Earnings
     *
     * @mbggenerated
     */
    public Integer getEarnings() {
        return earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Earnings
     *
     * @param earnings the value for aggsByHour.Earnings
     *
     * @mbggenerated
     */
    public void setEarnings(Integer earnings) {
        this.earnings = earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByHour.Dividends
     *
     * @return the value of aggsByHour.Dividends
     *
     * @mbggenerated
     */
    public Double getDividends() {
        return dividends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByHour.Dividends
     *
     * @param dividends the value for aggsByHour.Dividends
     *
     * @mbggenerated
     */
    public void setDividends(Double dividends) {
        this.dividends = dividends;
    }
}