package com.citi.shanghai.training.dataAnalyst.model;

import java.math.BigDecimal;

public class AggsByDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.symbolID
     *
     * @mbggenerated
     */
    private Integer symbolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Date
     *
     * @mbggenerated
     */
    private Integer date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.High
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.SplitFactor
     *
     * @mbggenerated
     */
    private Double splitfactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Earnings
     *
     * @mbggenerated
     */
    private Integer earnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggsByDay.Dividends
     *
     * @mbggenerated
     */
    private Double dividends;

    private Double increasePercentage;

    public Double getIncreasePercentage() {
        return increasePercentage;
    }

    public void setIncreasePercentage(Double increasePercentage) {
        this.increasePercentage = increasePercentage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.ID
     *
     * @return the value of aggsByDay.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.ID
     *
     * @param id the value for aggsByDay.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.symbolID
     *
     * @return the value of aggsByDay.symbolID
     *
     * @mbggenerated
     */
    public Integer getSymbolid() {
        return symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.symbolID
     *
     * @param symbolid the value for aggsByDay.symbolID
     *
     * @mbggenerated
     */
    public void setSymbolid(Integer symbolid) {
        this.symbolid = symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.symbol
     *
     * @return the value of aggsByDay.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.symbol
     *
     * @param symbol the value for aggsByDay.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Date
     *
     * @return the value of aggsByDay.Date
     *
     * @mbggenerated
     */
    public Integer getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Date
     *
     * @param date the value for aggsByDay.Date
     *
     * @mbggenerated
     */
    public void setDate(Integer date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Open
     *
     * @return the value of aggsByDay.Open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Open
     *
     * @param open the value for aggsByDay.Open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.High
     *
     * @return the value of aggsByDay.High
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.High
     *
     * @param high the value for aggsByDay.High
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Low
     *
     * @return the value of aggsByDay.Low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Low
     *
     * @param low the value for aggsByDay.Low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Close
     *
     * @return the value of aggsByDay.Close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Close
     *
     * @param close the value for aggsByDay.Close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Volume
     *
     * @return the value of aggsByDay.Volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Volume
     *
     * @param volume the value for aggsByDay.Volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.SplitFactor
     *
     * @return the value of aggsByDay.SplitFactor
     *
     * @mbggenerated
     */
    public Double getSplitfactor() {
        return splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.SplitFactor
     *
     * @param splitfactor the value for aggsByDay.SplitFactor
     *
     * @mbggenerated
     */
    public void setSplitfactor(Double splitfactor) {
        this.splitfactor = splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Earnings
     *
     * @return the value of aggsByDay.Earnings
     *
     * @mbggenerated
     */
    public Integer getEarnings() {
        return earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Earnings
     *
     * @param earnings the value for aggsByDay.Earnings
     *
     * @mbggenerated
     */
    public void setEarnings(Integer earnings) {
        this.earnings = earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggsByDay.Dividends
     *
     * @return the value of aggsByDay.Dividends
     *
     * @mbggenerated
     */
    public Double getDividends() {
        return dividends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggsByDay.Dividends
     *
     * @param dividends the value for aggsByDay.Dividends
     *
     * @mbggenerated
     */
    public void setDividends(Double dividends) {
        this.dividends = dividends;
    }
}