package com.citi.shanghai.training.dataAnalyst.model;

public class CalendarDate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.CalendarDate
     *
     * @mbggenerated
     */
    private String calendardate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.intDate
     *
     * @mbggenerated
     */
    private Integer intdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.dayNumber
     *
     * @mbggenerated
     */
    private Integer daynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.dayName
     *
     * @mbggenerated
     */
    private String dayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.shortDayName
     *
     * @mbggenerated
     */
    private String shortdayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.monthNumber
     *
     * @mbggenerated
     */
    private Integer monthnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.monthName
     *
     * @mbggenerated
     */
    private String monthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.shortMonthName
     *
     * @mbggenerated
     */
    private String shortmonthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.yearNumber
     *
     * @mbggenerated
     */
    private Integer yearnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.stringDate1
     *
     * @mbggenerated
     */
    private String stringdate1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calendar.stringDate2
     *
     * @mbggenerated
     */
    private String stringdate2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.CalendarDate
     *
     * @return the value of calendar.CalendarDate
     *
     * @mbggenerated
     */
    public String getCalendardate() {
        return calendardate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.CalendarDate
     *
     * @param calendardate the value for calendar.CalendarDate
     *
     * @mbggenerated
     */
    public void setCalendardate(String calendardate) {
        this.calendardate = calendardate == null ? null : calendardate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.intDate
     *
     * @return the value of calendar.intDate
     *
     * @mbggenerated
     */
    public Integer getIntdate() {
        return intdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.intDate
     *
     * @param intdate the value for calendar.intDate
     *
     * @mbggenerated
     */
    public void setIntdate(Integer intdate) {
        this.intdate = intdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.dayNumber
     *
     * @return the value of calendar.dayNumber
     *
     * @mbggenerated
     */
    public Integer getDaynumber() {
        return daynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.dayNumber
     *
     * @param daynumber the value for calendar.dayNumber
     *
     * @mbggenerated
     */
    public void setDaynumber(Integer daynumber) {
        this.daynumber = daynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.dayName
     *
     * @return the value of calendar.dayName
     *
     * @mbggenerated
     */
    public String getDayname() {
        return dayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.dayName
     *
     * @param dayname the value for calendar.dayName
     *
     * @mbggenerated
     */
    public void setDayname(String dayname) {
        this.dayname = dayname == null ? null : dayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.shortDayName
     *
     * @return the value of calendar.shortDayName
     *
     * @mbggenerated
     */
    public String getShortdayname() {
        return shortdayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.shortDayName
     *
     * @param shortdayname the value for calendar.shortDayName
     *
     * @mbggenerated
     */
    public void setShortdayname(String shortdayname) {
        this.shortdayname = shortdayname == null ? null : shortdayname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.monthNumber
     *
     * @return the value of calendar.monthNumber
     *
     * @mbggenerated
     */
    public Integer getMonthnumber() {
        return monthnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.monthNumber
     *
     * @param monthnumber the value for calendar.monthNumber
     *
     * @mbggenerated
     */
    public void setMonthnumber(Integer monthnumber) {
        this.monthnumber = monthnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.monthName
     *
     * @return the value of calendar.monthName
     *
     * @mbggenerated
     */
    public String getMonthname() {
        return monthname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.monthName
     *
     * @param monthname the value for calendar.monthName
     *
     * @mbggenerated
     */
    public void setMonthname(String monthname) {
        this.monthname = monthname == null ? null : monthname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.shortMonthName
     *
     * @return the value of calendar.shortMonthName
     *
     * @mbggenerated
     */
    public String getShortmonthname() {
        return shortmonthname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.shortMonthName
     *
     * @param shortmonthname the value for calendar.shortMonthName
     *
     * @mbggenerated
     */
    public void setShortmonthname(String shortmonthname) {
        this.shortmonthname = shortmonthname == null ? null : shortmonthname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.yearNumber
     *
     * @return the value of calendar.yearNumber
     *
     * @mbggenerated
     */
    public Integer getYearnumber() {
        return yearnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.yearNumber
     *
     * @param yearnumber the value for calendar.yearNumber
     *
     * @mbggenerated
     */
    public void setYearnumber(Integer yearnumber) {
        this.yearnumber = yearnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.stringDate1
     *
     * @return the value of calendar.stringDate1
     *
     * @mbggenerated
     */
    public String getStringdate1() {
        return stringdate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.stringDate1
     *
     * @param stringdate1 the value for calendar.stringDate1
     *
     * @mbggenerated
     */
    public void setStringdate1(String stringdate1) {
        this.stringdate1 = stringdate1 == null ? null : stringdate1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calendar.stringDate2
     *
     * @return the value of calendar.stringDate2
     *
     * @mbggenerated
     */
    public String getStringdate2() {
        return stringdate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calendar.stringDate2
     *
     * @param stringdate2 the value for calendar.stringDate2
     *
     * @mbggenerated
     */
    public void setStringdate2(String stringdate2) {
        this.stringdate2 = stringdate2 == null ? null : stringdate2.trim();
    }
}