package com.citi.shanghai.training.dataAnalyst.model;

public class PortfolioSymbols {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolioWithSymbols.portfolioID
     *
     * @mbggenerated
     */
    private Integer portfolioid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portfolioWithSymbols.symbolID
     *
     * @mbggenerated
     */
    private Integer symbolid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolioWithSymbols.portfolioID
     *
     * @return the value of portfolioWithSymbols.portfolioID
     *
     * @mbggenerated
     */
    public Integer getPortfolioid() {
        return portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolioWithSymbols.portfolioID
     *
     * @param portfolioid the value for portfolioWithSymbols.portfolioID
     *
     * @mbggenerated
     */
    public void setPortfolioid(Integer portfolioid) {
        this.portfolioid = portfolioid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column portfolioWithSymbols.symbolID
     *
     * @return the value of portfolioWithSymbols.symbolID
     *
     * @mbggenerated
     */
    public Integer getSymbolid() {
        return symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column portfolioWithSymbols.symbolID
     *
     * @param symbolid the value for portfolioWithSymbols.symbolID
     *
     * @mbggenerated
     */
    public void setSymbolid(Integer symbolid) {
        this.symbolid = symbolid;
    }
}