package com.citi.shanghai.training.dataAnalyst.model;

import java.math.BigDecimal;

public class Recoards {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.symbolID
     *
     * @mbggenerated
     */
    private Integer symbolid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.symbol
     *
     * @mbggenerated
     */
    private String symbol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Date
     *
     * @mbggenerated
     */
    private Integer date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Time
     *
     * @mbggenerated
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Open
     *
     * @mbggenerated
     */
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.High
     *
     * @mbggenerated
     */
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Low
     *
     * @mbggenerated
     */
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Close
     *
     * @mbggenerated
     */
    private Double close;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Volume
     *
     * @mbggenerated
     */
    private BigDecimal volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.SplitFactor
     *
     * @mbggenerated
     */
    private Double splitfactor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Earnings
     *
     * @mbggenerated
     */
    private Integer earnings;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Dividends
     *
     * @mbggenerated
     */
    private Double dividends;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.ID
     *
     * @return the value of records.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.ID
     *
     * @param id the value for records.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.symbolID
     *
     * @return the value of records.symbolID
     *
     * @mbggenerated
     */
    public Integer getSymbolid() {
        return symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.symbolID
     *
     * @param symbolid the value for records.symbolID
     *
     * @mbggenerated
     */
    public void setSymbolid(Integer symbolid) {
        this.symbolid = symbolid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.symbol
     *
     * @return the value of records.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.symbol
     *
     * @param symbol the value for records.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Date
     *
     * @return the value of records.Date
     *
     * @mbggenerated
     */
    public Integer getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Date
     *
     * @param date the value for records.Date
     *
     * @mbggenerated
     */
    public void setDate(Integer date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Time
     *
     * @return the value of records.Time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Time
     *
     * @param time the value for records.Time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Open
     *
     * @return the value of records.Open
     *
     * @mbggenerated
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Open
     *
     * @param open the value for records.Open
     *
     * @mbggenerated
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.High
     *
     * @return the value of records.High
     *
     * @mbggenerated
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.High
     *
     * @param high the value for records.High
     *
     * @mbggenerated
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Low
     *
     * @return the value of records.Low
     *
     * @mbggenerated
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Low
     *
     * @param low the value for records.Low
     *
     * @mbggenerated
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Close
     *
     * @return the value of records.Close
     *
     * @mbggenerated
     */
    public Double getClose() {
        return close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Close
     *
     * @param close the value for records.Close
     *
     * @mbggenerated
     */
    public void setClose(Double close) {
        this.close = close;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Volume
     *
     * @return the value of records.Volume
     *
     * @mbggenerated
     */
    public BigDecimal getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Volume
     *
     * @param volume the value for records.Volume
     *
     * @mbggenerated
     */
    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.SplitFactor
     *
     * @return the value of records.SplitFactor
     *
     * @mbggenerated
     */
    public Double getSplitfactor() {
        return splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.SplitFactor
     *
     * @param splitfactor the value for records.SplitFactor
     *
     * @mbggenerated
     */
    public void setSplitfactor(Double splitfactor) {
        this.splitfactor = splitfactor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Earnings
     *
     * @return the value of records.Earnings
     *
     * @mbggenerated
     */
    public Integer getEarnings() {
        return earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Earnings
     *
     * @param earnings the value for records.Earnings
     *
     * @mbggenerated
     */
    public void setEarnings(Integer earnings) {
        this.earnings = earnings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Dividends
     *
     * @return the value of records.Dividends
     *
     * @mbggenerated
     */
    public Double getDividends() {
        return dividends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Dividends
     *
     * @param dividends the value for records.Dividends
     *
     * @mbggenerated
     */
    public void setDividends(Double dividends) {
        this.dividends = dividends;
    }
}